import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './_components/providers/NextAuthProvider'

import "@tldraw/tldraw/tldraw.css"
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          {children}
          <Toaster className='!z-[33333]' />
        </body>
      </NextAuthProvider>
    </html>
  )
}
